// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYKv4KRnUHGq_31BSvjW5vP5CoQPsaY8',
    appId: '1:1040809661139:android:e46d3528cdfe19ba2dfa26',
    messagingSenderId: '1040809661139',
    projectId: 'medicine-cabinet-886d5',
    storageBucket: 'medicine-cabinet-886d5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Ke1DHys8OTILHa1h_iInqStG0Ph92WU',
    appId: '1:1040809661139:ios:108b4db1bf04bb512dfa26',
    messagingSenderId: '1040809661139',
    projectId: 'medicine-cabinet-886d5',
    storageBucket: 'medicine-cabinet-886d5.firebasestorage.app',
    androidClientId: '1040809661139-1fm32heii9dfrrfsbgep3sc862pam897.apps.googleusercontent.com',
    iosClientId: '1040809661139-j8g1je199bjbi9llcf8ulc16kr2j0gu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicine-cabinet',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVibx_BVQBw7pHFVaSHKHN_eYJhR7GLgA',
    appId: '1:1040809661139:web:dd51d108104a63062dfa26',
    messagingSenderId: '1040809661139',
    projectId: 'medicine-cabinet-886d5',
    authDomain: 'medicine-cabinet-886d5.firebaseapp.com',
    storageBucket: 'medicine-cabinet-886d5.firebasestorage.app',
    measurementId: 'G-53KNCVBQ7F',
  );
}
